spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:tcp://localhost/~/Board
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: cloud #local or cloud

  mvc:
    path-match:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace



